version: '3.8'

volumes:
  audio-data:

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_SIZE=small
      - DEVICE=cuda
      - COMPUTE_TYPE=float16
      - LOG_LEVEL=INFO
      - ALLOWED_EXTENSIONS=mp3,wav,m4a,flac,ogg,wma,aac,mp4
    volumes:
      - ./logs:/app/logs
      - audio-data:/app/shared_audio
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  worker:
    build: .
    command: python batch_worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_SIZE=small
      - DEVICE=cuda
      - COMPUTE_TYPE=float16
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - audio-data:/app/shared_audio
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped