version: '3.8'

services:
  whisper-stt:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_SIZE=small
      - DEVICE=cuda
      - COMPUTE_TYPE=float16
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
